//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatchClient.ClinentDbModel.DdModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAPClientPatch
    {
        public int PatchScriptId { get; set; }
        public int MarketId { get; set; }
        public string MarketSN { get; set; }
        public string PatchSeverity { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public Nullable<int> PatchState { get; set; }
        public string PatchName { get; set; }
    }
}
